Fix spelling errors in binaries.
FreeFem/FreeFem-sources pull request #188
Opened 2021-07-28 18:03 UTC by mzf-guest

Hello,

here the patch from the Debian package that removes common spelling errors in the generated binaries.

Best,

François

2021-08-04 09:27 UTC, prj- requested changes
Please revert the changes in `readme/HISTORY` and `readme/HISTORY_BEFORE_2005`. These are legacy files that should not be updated anymore. Thank you for your contribution.

2021-08-04 09:27 UTC, prj- commented on src/bamglib/Mesh2.cpp
> +    cout << "  -- adaptmesh Regularly:  Nb triangles " << nt << " , h  min " << hmin << " , h max "
```suggestion
    cout << "  -- adaptmesh statistics:  Nb triangles " << nt << " , h  min " << hmin << " , h max "
```

2021-08-04 09:27 UTC, prj- commented on src/fflib/lgfem.cpp
> +              ExecError("periodic: Sorry one edge is losted ");
```suggestion
              ExecError("periodic: Sorry one edge is lost");
```

2021-08-10 12:39 UTC, mzf-guest commented on src/fflib/lgfem.cpp
> +              ExecError("periodic: Sorry one edge is losted ");
Done!

2021-08-10 12:39 UTC, mzf-guest commented on src/bamglib/Mesh2.cpp
> +    cout << "  -- adaptmesh Regularly:  Nb triangles " << nt << " , h  min " << hmin << " , h max "
Done!

2021-08-10 12:39 UTC, mzf-guest commented
> Please revert the changes in `readme/HISTORY` and `readme/HISTORY_BEFORE_2005`. These are legacy files that should not be updated anymore. Thank you for your contribution.

Done!

2021-08-10 12:43 UTC, merged

2021-08-10 12:44 UTC, prj- commented
Thank you for your contribution.