diffusion-hpddm-2d-PETSc.edp
FreeFem/FreeFem-sources pull request #302
Opened 2024-03-05 10:52 UTC by prj-

2024-03-05 11:11 UTC, FredericN requested changes
J'aurais aimé proposé les changements proposés directement dans le code et pas en tant que commentaires. Mais je ne suis pas "fluent" en Github.

2024-03-05 11:11 UTC, FredericN commented on examples/hpddm/diffusion-hpddm-2d-PETSc.edp
> +//  run with MPI: ff-mpirun -np 4 hpddm.edp -ns -pc_type lu
il faut ajouter -wg dans la ligne de commande.

2024-03-05 11:11 UTC, FredericN commented on examples/hpddm/diffusion-hpddm-2d-PETSc.edp
> +set(A, sparams = "-pc_hpddm_levels_1_sub_pc_type lu -pc_hpddm_levels_1_st_pc_factor_mat_solver_type mumps -pc_hpddm_levels_1_eps_nev 10 -pc_hpddm_define_subdomains -pc_hpddm_has_neumann -ksp_type gmr
il faut ajouter -ksp_pc_side right

2024-03-05 11:11 UTC, FredericN commented on examples/hpddm/diffusion-hpddm-2d-PETSc.edp
> +//  -ksp_type gmres : GMRES is the Krylov solver
il faut ajouter 
// -ksp_pc_side right : the preconditioner is applied on the right (much safer option than left)

2024-03-05 11:11 UTC, FredericN commented on examples/hpddm/diffusion-hpddm-2d-PETSc.edp
> +//  run with MPI: ff-mpirun -np 4 hpddm.edp -ns -pc_type lu
Il faut changer le nom du fichier en 
diffusion-hpddm-2d-PETSc.edp

2024-03-05 11:11 UTC, FredericN commented on examples/hpddm/diffusion-hpddm-2d-PETSc.edp
> +// Recall that A is Mat a distributed matrix and Neumann is a local one. The equal sign '=' means in fact that the entries of the distributed matrix A are filled with the entries of the local Neumann
Question: il y a effectivement une copie des données ou simplement un passage de pointeur?

2024-03-05 11:11 UTC, FredericN commented on examples/hpddm/diffusion-hpddm-2d-PETSc.edp
Il faudrait peut-être aussi ajouter le même exemple en 3D situation dans laquelle les solveurs directs sont très vite insuffisants.

2024-03-05 11:11 UTC, FredericN commented on examples/hpddm/diffusion-hpddm-2d-PETSc.edp
> +matrix Neumann = vPb(Wh, Wh); // local matrix for the Neumann in the subdomain
Changer le commentaire en:
// local matrix with Neumann boundary condition on the interface of the subdomain

2024-03-24 16:52 UTC, prj- commented
Dear @FredericN, following our conversation offline, I made the following adjustments:
1. new example `diffusion-hpddm-2d-PETSc.edp` based on your file `hpddm2Dtau.edp`
- switch from `tgv = -1` to `tgv = -2`
- switch from LU to Cholesky
- switch from RAS to ASM
- switch from deflated coarse correction to additive coarse correction
- switch from GMRES to CG
- switch from `-ksp_monitor` to `-ksp_monitor_singular_value` to get an estimate of the condition number of the preconditioner operator
2. new example `diffusion-hpddm-3d-PETSc.edp` based on your file `hpddm3D.edp`

Please either make further comments or approve the PR and I'll merge it.

2024-03-26 12:54 UTC, FredericN commented on examples/hpddm/diffusion-hpddm-2d-PETSc.edp
> +//  -pc_hpddm_has_neumann                                  - https://petsc.org/release/manualpages/PC/PCHPDDMHasNeumannMat/
```suggestion
//  -pc_hpddm_has_neumann                                  - 
local Neumann matrices necessary to GenEO have already been computed    https://petsc.org/release/manualpages/PC/PCHPDDMHasNeumannMat/
```

2024-03-26 12:55 UTC, FredericN commented on examples/hpddm/diffusion-hpddm-2d-PETSc.edp
> +//  -pc_hpddm_define_subdomains                            - https://petsc.org/release/manualpages/PC/PCHPDDMSetSTShareSubKSP/
```suggestion
//  -pc_hpddm_define_subdomains      HPDDM will use the existing subdomains                      - https://petsc.org/release/manualpages/PC/PCHPDDMSetSTShareSubKSP/
```

2024-03-26 12:56 UTC, FredericN commented on examples/hpddm/diffusion-hpddm-2d-PETSc.edp
> +//  -ksp_type cg                                           - https://petsc.org/release/manualpages/KSP/KSPType/
```suggestion
//  -ksp_type cg    The Krylov solver is the Conjugate Gradient                                        - https://petsc.org/release/manualpages/KSP/KSPType/
```

2024-03-26 12:59 UTC, FredericN commented on examples/hpddm/diffusion-hpddm-3d-PETSc.edp
> +//  -pc_hpddm_has_neumann                                  - https://petsc.org/release/manualpages/PC/PCHPDDMHasNeumannMat/
```suggestion
//  -pc_hpddm_has_neumann    local Neumann matrices necessary to GenEO have already been computed                                  - https://petsc.org/release/manualpages/PC/PCHPDDMHasNeumannMat/
```

2024-03-26 12:59 UTC, FredericN commented on examples/hpddm/diffusion-hpddm-3d-PETSc.edp
> +//  -pc_hpddm_define_subdomains                            - https://petsc.org/release/manualpages/PC/PCHPDDMSetSTShareSubKSP/
```suggestion
//  -pc_hpddm_define_subdomains   HPDDM will use the existing subdomains                          - https://petsc.org/release/manualpages/PC/PCHPDDMSetSTShareSubKSP/
```

2024-03-26 12:59 UTC, FredericN commented on examples/hpddm/diffusion-hpddm-3d-PETSc.edp
> +//  -ksp_type gmres                                        - https://petsc.org/release/manualpages/KSP/KSPType/
```suggestion   The Krylov solver is GMRES
//  -ksp_type gmres                                        - https://petsc.org/release/manualpages/KSP/KSPType/
```

2024-03-26 13:00 UTC, FredericN commented on examples/hpddm/diffusion-hpddm-3d-PETSc.edp
> +//  -ksp_pc_side right                                     - https://petsc.org/release/manualpages/PC/PCSide/
```suggestion  right preconditioning is much safer than left preconditioning
//  -ksp_pc_side right                                     - https://petsc.org/release/manualpages/PC/PCSide/
```

2024-03-26 13:06 UTC, FredericN commented on examples/hpddm/diffusion-hpddm-2d-PETSc.edp
> +// Options for hpddm via PETSc are given in: https://petsc.org/release/manualpages/PC/PCHPDDM/
```suggestion
// Options for hpddm via PETSc are given in: https://petsc.org/release/manualpages/PC/PCHPDDM/
// As far as hpddm is concerned, this script implements the GenEO method with a threshold selection criteria for the construction of the coarse. 
```

2024-03-26 13:07 UTC, FredericN commented on examples/hpddm/diffusion-hpddm-3d-PETSc.edp
> +// Options for hpddm via PETSc are given in: https://petsc.org/release/manualpages/PC/PCHPDDM/
```suggestion
// Options for hpddm via PETSc are given in: https://petsc.org/release/manualpages/PC/PCHPDDM/
// As far as hpddm is concerned, this script implements the GenEO method with a fixed number of eigenvectors for the coarse space. 
```

2024-03-27 15:01 UTC, merged